version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: keycloakmpd
    ports:
      - 8081:8080
      - 8443:8443
    restart: unless-stopped
    environment:
      # Credentials for admin account
      # -----------------------------
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    volumes:
      - C:\tmp\docker\mpd\keycloak\data:/opt/jboss/keycloak/standalone/data
      - C:\tmp\docker\mpd\keycloak\logs:/opt/jboss/keycloak/standalone/log

volumes:
  keycloak_data:
  keycloak_logs:

  
# docker compose -f docker/dc_kcmpd.yaml -p dc_kcmpd up -d