version: '3'
services:
  keycloack:
    image: quay.io/keycloak/keycloak:12.0.2
    #image: quay.io/keycloak/keycloak:21.1.1
    #comando docker: docker compose up -d
    container_name: keycloak
    ports:
      - 8081:8080
      - 8443:8443
    restart: unless-stopped
    environment:
      # Credentials for admin account
      # -----------------------------
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - keycloak_logs:/opt/jboss/keycloak/standalone/log


volumes:
  keycloak_data:
  keycloak_logs:

  
      # Credentials for storing into an external database
      # -------------------------------------------------
      # DB_VENDOR: "mysql"
      # DB_ADDR: 
      # DB_PORT:
      # DB_DATABASE: 
      # DB_USER:
      # DB_PASSWORD: 